<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Items\Controllers\ItemsController;
use App\Http\ApiV1\Modules\Providers\Controllers\ProvidersController;
use Illuminate\Support\Facades\Route;

Route::post('providers', [ProvidersController::class, 'create']);
Route::get('providers/{id}', [ProvidersController::class, 'get'])->name('getProvider');
Route::put('providers/{id}', [ProvidersController::class, 'update']);
Route::delete('providers/{id}', [ProvidersController::class, 'delete']);
Route::post('items', [ItemsController::class, 'create']);
Route::get('items/{id}', [ItemsController::class, 'get'])->name('getItem');
Route::put('items/{id}', [ItemsController::class, 'update']);
Route::delete('items/{id}', [ItemsController::class, 'delete']);
