<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Providers\Controllers\ProvidersController;
use Illuminate\Support\Facades\Route;

Route::post('providers', [ProvidersController::class, 'create']);
Route::get('providers/{id}', [ProvidersController::class, 'get'])->name('getItem');
