version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"
    depends_on:
      - app
    networks:
      - providers
    container_name: providers-nginx

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    networks:
      - providers
    container_name: providers

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: providers
      POSTGRES_USER: miet
      POSTGRES_PASSWORD: miet
    networks:
      - providers
    container_name: providers-db

networks:
  providers:
    driver: bridge
