openapi: 3.0.3
info:
  title: Providers service
  contact:
    name: API Support
    url: https://ensi.tech/contacts
    email: mail@greensight.ru
  version: 1.0.0
  description: Providers service description
servers:
  - url: /api/v1
tags:
  - name: providers
    description: Providers
paths:      
  /providers:
    post:
      tags:
        - providers
      operationId: createProvider
      x-lg-handler: 'App\Http\ApiV1\Modules\Providers\Controllers\ProvidersController@create'
      summary: Create объекта типа Provider
      description: Create объекта типа Provider description
      requestBody:
        content:
          application/json:
            schema:
              $ref: './providers/providers.yaml#/CreateProviderRequest'
      responses:
        "201":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './providers/providers.yaml#/ProviderResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/ServerError' 
          
  /providers/{id}:
    get:
      tags:
        - providers
      operationId: getProvider
      x-lg-handler: 'App\Http\ApiV1\Modules\Providers\Controllers\ProvidersController@get'
      x-lg-route-name: 'getProvider'
      x-lg-skip-request-generation: true
      summary: Получение объекта типа Provider
      description: Получение объекта типа Provider description
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './providers/providers.yaml#/ProviderResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
          
    put:
      tags:
        - providers
      operationId: updateProvider
      x-lg-handler: 'App\Http\ApiV1\Modules\Providers\Controllers\ProvidersController@update'
      summary: Update объекта типа Provider
      description: Update объекта типа Provider description
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './providers/providers.yaml#/UpdateProviderRequest'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './providers/providers.yaml#/ProviderResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
          
    delete:
      tags:
        - providers
      operationId: deleteProvider
      x-lg-handler: 'App\Http\ApiV1\Modules\Providers\Controllers\ProvidersController@delete'
      summary: Delete объекта типа Provider
      description: Delete объекта типа Provider description
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyDataResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
          
components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
